### ISSUE TITLE
[REQ] \e\ and build (Colab)Notebook

### ISSUE THREAD

**Issue by forart** [xiaomi-cepheus/device_xiaomi_cepheus#1]
Hi there,
it would be great to have an [\e\ (aka deGoogled-Lineage)](https://e.foundation/) build for _cephus_ too.

Someone opened a request 3ad @ [\e\ community](https://community.e.foundation/) for this device that we replied by linking your repos:

https://community.e.foundation/t/xiaomi-mi-9-request-for-e-os/33460

If you need, here's a couple of interesting guides that may help to build it:
https://doc.e.foundation/support-topics/build-e
https://community.e.foundation/t/howto-building-e-roms-a-beginners-guide/26371

Last but not least, we've also suggested (check [here](https://community.e.foundation/t/automated-builds-v-machine/43336)) to setup a "build (V)Machine" by modding these colab notebooks to made them device agnostic:
https://github.com/viam1-dev/colab_lineage_build
https://github.com/T110-android/colab_build

Hope can "inspire" you.

Thanks in advance.

**Comment by RDS-007** [comment]
Hii there @forart . I cant make los build because I don`t have server and even if I build it then I will not maintain it for a long time.

**Comment by forart** [comment]
Thanks for your fast reply and don't worry: do what you can.

Anyway, as said, the "colab notebook" approach could be an interesting solution for those who wanna build themselves but don't know how or don't have sufficient resources.

Thanks again for the volunteer work you do.

**Comment by RDS-007** [comment]
> 

welcome. I do make xtended and it`s gonna be official soon and you can degoogle it with root permissions and use microg if you wanted to
